version: '3.3'
services:
    deemix:
        image: registry.gitlab.com/bockiii/deemix-docker
        container_name: deemix
        volumes:
            - /path/to/Music/:/downloads #Your Music Location
            - ./config/:/config
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK_SET=022
        ports:
            - 6595:6595

